### YamlMime:ManagedReference
items:
- uid: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs
  id: FirstChanceExceptionEventArgs
  children:
  - System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.#ctor(System.Exception)
  - System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception
  langs:
  - csharp
  name: FirstChanceExceptionEventArgs
  nameWithType: FirstChanceExceptionEventArgs
  fullName: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs
  type: Class
  summary: "Disponibiliza dados para o evento de notificação que é gerado quando uma gerido pela primeira vez ocorre uma exceção, antes do language runtime começa a procurar processadores de eventos."
  remarks: "Esta classe fornece o processador de exceções para o <xref:System.AppDomain.FirstChanceException?displayProperty=fullName>evento com acesso a exceção.</xref:System.AppDomain.FirstChanceException?displayProperty=fullName>"
  example:
  - "The following example creates a series of application domains named `Child_0` through `Child_3`, with a `Worker` object in each application domain. Each `Worker` object has a reference to the `Worker` object in the next application domain, except for the `Worker` in the last application domain. The <xref:System.AppDomain.FirstChanceException> event is handled in all application domains except `Child_1`.  \n  \n When the application domains have been created, the default application domain calls the `TestException` method for the first child application domain. Each `Worker` object calls the `TestException` method for the next, until the last `Worker` throws an exception that is either handled or unhandled. Thus, the current thread passes through all the application domains, and `TestException` is added to the stack in each application domain.  \n  \n When the last `Worker` object handles the exception, the <xref:System.AppDomain.FirstChanceException> event is raised only in the last application domain. The other application domains never get a chance to handle the exception, so the event is not raised.  \n  \n When the last `Worker` object does not handle the exception, the <xref:System.AppDomain.FirstChanceException> event is raised in each application domain that has an event handler. After each event handler has finished, the stack continues to unwind until the exception is caught by the default application domain.  \n  \n> [!NOTE]\n>  To see how the stack display grows as the event is raised closer and closer to the default application domain, change `e.Exception.Message` to `e.Exception` in the `FirstChanceHandler` event handlers. Notice that when `TestException` is called across application domain boundaries, it appears twice: once for the proxy and once for the stub.  \n  \n [!code-vb[System.AppDomain.FirstChanceException#1](~/add/codesnippet/visualbasic/t-system.runtime.excepti_1.vb)]\n [!code-cs[System.AppDomain.FirstChanceException#1](~/add/codesnippet/csharp/t-system.runtime.excepti_1.cs)]"
  syntax:
    content: 'public class FirstChanceExceptionEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.#ctor(System.Exception)
  id: '#ctor(System.Exception)'
  parent: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs
  langs:
  - csharp
  name: FirstChanceExceptionEventArgs(Exception)
  nameWithType: FirstChanceExceptionEventArgs.FirstChanceExceptionEventArgs(Exception)
  fullName: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.FirstChanceExceptionEventArgs(Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.ExceptionServices
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs&quot;> </xref> classe com uma exceção especificada."
  remarks: "Este construtor é chamado pelo runtime de idioma comum, não pelo código da aplicação."
  syntax:
    content: public FirstChanceExceptionEventArgs (Exception exception);
    parameters:
    - id: exception
      type: System.Exception
      description: "A exceção que apenas foi acionada por código gerido e que será examinado pelo <xref href=&quot;System.AppDomain.UnhandledException&quot;> </xref> eventos."
  overload: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception
  id: Exception
  parent: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs
  langs:
  - csharp
  name: Exception
  nameWithType: FirstChanceExceptionEventArgs.Exception
  fullName: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Runtime.ExceptionServices
  summary: "O objeto gerido exceção que corresponde a exceção emitida no código gerido."
  remarks: "O método que processa o <xref:System.AppDomain.UnhandledException?displayProperty=fullName>evento pode examinar a exceção e efetuar o registo adequado ou outros serviços de notificação.</xref:System.AppDomain.UnhandledException?displayProperty=fullName>       Para o código de exemplo, consulte <xref:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs>.</xref:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs>"
  syntax:
    content: public Exception Exception { get; }
    return:
      type: System.Exception
      description: "A exceção recentemente iniciada."
  overload: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.#ctor(System.Exception)
  parent: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs
  isExternal: false
  name: FirstChanceExceptionEventArgs(Exception)
  nameWithType: FirstChanceExceptionEventArgs.FirstChanceExceptionEventArgs(Exception)
  fullName: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.FirstChanceExceptionEventArgs(Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception
  parent: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs
  isExternal: false
  name: Exception
  nameWithType: FirstChanceExceptionEventArgs.Exception
  fullName: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception
- uid: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.#ctor*
  parent: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs
  isExternal: false
  name: FirstChanceExceptionEventArgs
  nameWithType: FirstChanceExceptionEventArgs.FirstChanceExceptionEventArgs
- uid: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception*
  parent: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs
  isExternal: false
  name: Exception
  nameWithType: FirstChanceExceptionEventArgs.Exception
