### YamlMime:ManagedReference
items:
- uid: System.ApplicationException
  id: ApplicationException
  children:
  - System.ApplicationException.#ctor
  - System.ApplicationException.#ctor(System.String)
  - System.ApplicationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.ApplicationException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: ApplicationException
  nameWithType: ApplicationException
  fullName: System.ApplicationException
  type: Class
  summary: "Serve como a classe base para exceções definido pela aplicação."
  remarks: >-
    > [!IMPORTANT]

    >  You should derive custom exceptions from the <xref:System.Exception> class rather than the ApplicationException class.  You should not throw an ApplicationException exception in your code, and you should not catch an ApplicationException exception unless you intend to re-throw the original exception.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public class ApplicationException : Exception
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ApplicationException.#ctor
  id: '#ctor'
  parent: System.ApplicationException
  langs:
  - csharp
  name: ApplicationException()
  nameWithType: ApplicationException.ApplicationException()
  fullName: System.ApplicationException.ApplicationException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ApplicationException&quot;> </xref> classe."
  remarks: "Este construtor inicializa a <xref:System.Exception.Message%2A>propriedade da instância do novo a uma mensagem fornecido pelo sistema que descreve o erro, tal como &quot;aplicação Ocorreu um erro.&quot;</xref:System.Exception.Message%2A> Esta mensagem tem em consideração o idioma atual do sistema.       A tabela seguinte mostra os valores de propriedade inicial para uma instância do <xref:System.ApplicationException>.</xref:System.ApplicationException>      | Propriedade | Valor |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Uma referência nula (`Nothing` no Visual Basic). |   | <xref:System.Exception.Message%2A>| A cadeia de mensagem de erro localizado. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ApplicationException ();
    parameters: []
  overload: System.ApplicationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ApplicationException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ApplicationException
  langs:
  - csharp
  name: ApplicationException(String)
  nameWithType: ApplicationException.ApplicationException(String)
  fullName: System.ApplicationException.ApplicationException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ApplicationException&quot;> </xref> classe com uma mensagem de erro especificado."
  remarks: "O conteúdo a `message` parâmetro se destina a ser compreendidos pela entidade humans. O autor da chamada deste construtor não é necessária para se certificar de que esta cadeia tem foram localizada da cultura atual do sistema.       Esta mensagem tem em consideração o idioma atual do sistema.       A tabela seguinte mostra os valores de propriedade inicial para uma instância do <xref:System.ApplicationException>.</xref:System.ApplicationException>      | Propriedade | Valor |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Uma referência nula (`Nothing` no Visual Basic). |   | `Message`| A cadeia de mensagem de erro. |</xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ApplicationException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Uma mensagem que descreve o erro."
  overload: System.ApplicationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ApplicationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.ApplicationException
  langs:
  - csharp
  name: ApplicationException(SerializationInfo,StreamingContext)
  nameWithType: ApplicationException.ApplicationException(SerializationInfo,StreamingContext)
  fullName: System.ApplicationException.ApplicationException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ApplicationException&quot;> </xref> classe com dados serializados."
  remarks: "Este construtor é chamado durante a desserialização para reconstitute o objeto de exceção transmitido através de uma transmissão em fluxo. Para obter mais informações, consulte [XML e serialização SOAP](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: protected ApplicationException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "O objeto que contém os dados de objecto serializado."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "As nível contextual das informações sobre a origem ou destino."
  overload: System.ApplicationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ApplicationException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.ApplicationException
  langs:
  - csharp
  name: ApplicationException(String,Exception)
  nameWithType: ApplicationException.ApplicationException(String,Exception)
  fullName: System.ApplicationException.ApplicationException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ApplicationException&quot;> </xref> classe com uma mensagem de erro especificado e uma referência a exceção interna que é a causa desta exceção."
  remarks: "O conteúdo a `message` parâmetro se destina a ser compreendidos pela entidade humans. O autor da chamada deste construtor não é necessária para se certificar de que esta cadeia tem foram localizada da cultura atual do sistema.       Uma exceção que é acionada como um resultado direto de uma exceção anterior deve incluir uma referência a exceção anterior no <xref:System.Exception.InnerException%2A>propriedade.</xref:System.Exception.InnerException%2A> O <xref:System.Exception.InnerException%2A>propriedade devolve o mesmo valor que é transmitido no construtor ou uma referência nula se o <xref:System.Exception.InnerException%2A>propriedade não fornecer o valor da exceção interna para o construtor.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       A tabela seguinte mostra os valores de propriedade inicial para uma instância do <xref:System.ApplicationException>.</xref:System.ApplicationException>      | Propriedade | Valor |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| A referência a exceção interna. |   | <xref:System.Exception.Message%2A>| A cadeia de mensagem de erro. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ApplicationException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "A mensagem de erro que explique a razão para a exceção."
    - id: innerException
      type: System.Exception
      description: "A exceção é a causa da exceção atual. Se o `innerException` parâmetro não é uma referência nula, a exceção atual num <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> bloco que processa a exceção interna."
  overload: System.ApplicationException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.ApplicationException.#ctor
  parent: System.ApplicationException
  isExternal: false
  name: ApplicationException()
  nameWithType: ApplicationException.ApplicationException()
  fullName: System.ApplicationException.ApplicationException()
- uid: System.ApplicationException.#ctor(System.String)
  parent: System.ApplicationException
  isExternal: false
  name: ApplicationException(String)
  nameWithType: ApplicationException.ApplicationException(String)
  fullName: System.ApplicationException.ApplicationException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ApplicationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.ApplicationException
  isExternal: false
  name: ApplicationException(SerializationInfo,StreamingContext)
  nameWithType: ApplicationException.ApplicationException(SerializationInfo,StreamingContext)
  fullName: System.ApplicationException.ApplicationException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.ApplicationException.#ctor(System.String,System.Exception)
  parent: System.ApplicationException
  isExternal: false
  name: ApplicationException(String,Exception)
  nameWithType: ApplicationException.ApplicationException(String,Exception)
  fullName: System.ApplicationException.ApplicationException(String,Exception)
- uid: System.ApplicationException.#ctor*
  parent: System.ApplicationException
  isExternal: false
  name: ApplicationException
  nameWithType: ApplicationException.ApplicationException
