### YamlMime:ManagedReference
items:
- uid: System.ExecutionEngineException
  id: ExecutionEngineException
  children:
  - System.ExecutionEngineException.#ctor
  - System.ExecutionEngineException.#ctor(System.String)
  - System.ExecutionEngineException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: ExecutionEngineException
  nameWithType: ExecutionEngineException
  fullName: System.ExecutionEngineException
  type: Class
  summary: "The exception that is thrown when there is an internal error in the execution engine of the common language runtime. This class cannot be inherited."
  remarks: "There is no non-obsolete alternative to ExecutionEngineException. If further execution of your application cannot be sustained, use the <xref:System.Environment.FailFast%2A> method."
  syntax:
    content: >-
      [System.Obsolete("This type previously indicated an unspecified fatal error in the runtime. The runtime no longer raises this exception so this type is obsolete.")]

      [System.Runtime.InteropServices.ComVisible(true)]

      public sealed class ExecutionEngineException : SystemException
  inheritance:
  - System.Exception
  - System.SystemException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ExecutionEngineException.#ctor
  id: '#ctor'
  parent: System.ExecutionEngineException
  langs:
  - csharp
  name: ExecutionEngineException()
  nameWithType: ExecutionEngineException.ExecutionEngineException()
  fullName: System.ExecutionEngineException.ExecutionEngineException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Initializes a new instance of the <xref href=&quot;System.ExecutionEngineException&quot;></xref> class."
  remarks: "This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as &quot;Internal error occurred.&quot; This message takes into account the current system culture.       The following table shows the initial property values for an instance of <xref:System.ExecutionEngineException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|   |<xref:System.Exception.Message%2A>|The localized error message string.|"
  syntax:
    content: public ExecutionEngineException ();
    parameters: []
  overload: System.ExecutionEngineException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ExecutionEngineException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ExecutionEngineException
  langs:
  - csharp
  name: ExecutionEngineException(String)
  nameWithType: ExecutionEngineException.ExecutionEngineException(String)
  fullName: System.ExecutionEngineException.ExecutionEngineException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Initializes a new instance of the <xref href=&quot;System.ExecutionEngineException&quot;></xref> class with a specified error message."
  remarks: "This constructor initializes the <xref:System.Exception.Message%2A?displayProperty=fullName> property of the new exception using the `message` parameter. The content of `message` is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.       The following table shows the initial property values for an instance of <xref:System.ExecutionEngineException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|   |<xref:System.Exception.Message%2A>|The error message string.|"
  syntax:
    content: public ExecutionEngineException (string message);
    parameters:
    - id: message
      type: System.String
      description: "The message that describes the error."
  overload: System.ExecutionEngineException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ExecutionEngineException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.ExecutionEngineException
  langs:
  - csharp
  name: ExecutionEngineException(String,Exception)
  nameWithType: ExecutionEngineException.ExecutionEngineException(String,Exception)
  fullName: System.ExecutionEngineException.ExecutionEngineException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Initializes a new instance of the <xref href=&quot;System.ExecutionEngineException&quot;></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception."
  remarks: "An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or a null reference (`Nothing` in Visual Basic) if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.       The following table shows the initial property values for an instance of <xref:System.ExecutionEngineException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|The inner exception reference.|   |<xref:System.Exception.Message%2A>|The error message string.|"
  syntax:
    content: public ExecutionEngineException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "The error message that explains the reason for the exception."
    - id: innerException
      type: System.Exception
      description: "The exception that is the cause of the current exception. If the `innerException` parameter is not a null reference (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;></xref> in Visual Basic), the current exception is raised in a <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;></xref> block that handles the inner exception."
  overload: System.ExecutionEngineException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.SystemException
  isExternal: false
  name: System.SystemException
- uid: System.ExecutionEngineException.#ctor
  parent: System.ExecutionEngineException
  isExternal: false
  name: ExecutionEngineException()
  nameWithType: ExecutionEngineException.ExecutionEngineException()
  fullName: System.ExecutionEngineException.ExecutionEngineException()
- uid: System.ExecutionEngineException.#ctor(System.String)
  parent: System.ExecutionEngineException
  isExternal: false
  name: ExecutionEngineException(String)
  nameWithType: ExecutionEngineException.ExecutionEngineException(String)
  fullName: System.ExecutionEngineException.ExecutionEngineException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ExecutionEngineException.#ctor(System.String,System.Exception)
  parent: System.ExecutionEngineException
  isExternal: false
  name: ExecutionEngineException(String,Exception)
  nameWithType: ExecutionEngineException.ExecutionEngineException(String,Exception)
  fullName: System.ExecutionEngineException.ExecutionEngineException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.ExecutionEngineException.#ctor*
  parent: System.ExecutionEngineException
  isExternal: false
  name: ExecutionEngineException
  nameWithType: ExecutionEngineException.ExecutionEngineException
